#!/usr/bin/env bash

function find_base_dir {
  local dir_name
  local python_dir
  dir_name=$(dirname "$0")
  # NOTE(yoctozepto): Fix the case where dir_name is a symlink and VIRTUAL_ENV might not be. This
  # happens with pyenv-virtualenv, see https://bugs.launchpad.net/kolla-ansible/+bug/1903887
  dir_name=$(readlink -e "$dir_name")
  python_dir="python${ansible_python_version}"
  if [ ! -z "$CONDA_DEFAULT_ENV" ]; then
    BASEDIR=$(echo $(dirname $(which python)) | sed 's/.\{4\}$//')"/share/kolla-ansible"
  elif [ -z "$SNAP" ]; then
    if [[ ${dir_name} == "/usr/bin" ]]; then
      if test -f /usr/lib/${python_dir}/*-packages/kolla-ansible.egg-link; then
        # Editable install.
        BASEDIR="$(head -n1 /usr/lib/${python_dir}/*-packages/kolla-ansible.egg-link)"
      else
        BASEDIR=/usr/share/kolla-ansible
      fi
    elif [[ ${dir_name} == "/usr/local/bin" ]]; then
      if test -f /usr/local/lib/${python_dir}/*-packages/kolla-ansible.egg-link; then
        # Editable install.
        BASEDIR="$(head -n1 /usr/local/lib/${python_dir}/*-packages/kolla-ansible.egg-link)"
      else
        BASEDIR=/usr/local/share/kolla-ansible
      fi
    elif [[ ${dir_name} == ~/.local/bin ]]; then
      if test -f ~/.local/lib/${python_dir}/*-packages/kolla-ansible.egg-link; then
        # Editable install.
        BASEDIR="$(head -n1 ~/.local/lib/${python_dir}/*-packages/kolla-ansible.egg-link)"
      else
        BASEDIR=~/.local/share/kolla-ansible
      fi
    elif [[ -n ${VIRTUAL_ENV} ]] && [[ ${dir_name} == "$(readlink -e "${VIRTUAL_ENV}/bin")" ]]; then
      if test -f ${VIRTUAL_ENV}/lib/${python_dir}/site-packages/kolla-ansible.egg-link; then
        # Editable install.
        BASEDIR="$(head -n1 ${VIRTUAL_ENV}/lib/${python_dir}/*-packages/kolla-ansible.egg-link)"
      else
        BASEDIR="${VIRTUAL_ENV}/share/kolla-ansible"
      fi
    else
      # Running from sources (repo).
      BASEDIR="$(dirname ${dir_name})"
    fi
  else
    BASEDIR="$SNAP/share/kolla-ansible"
  fi

  echo "[DEBUG] Using BASEDIR=$BASEDIR"
}